
// auto generate

import { LPRECT, LPPAINTSTRUCT, RECT, PBSMINFO, LPMSG, DEVMODEA, DEVMODEW, LPPOINT, PCHANGEFILTERSTRUCT, LPCDLGTEMPLATEA, LPCDLGTEMPLATEW, LPACCEL, PICONINFO, PGESTUREINFO, LPCMENUITEMINFOA, LPCMENUITEMINFOW, PRAWINPUT, MSG, LPTPMPARAMS, LPTRACKMOUSEEVENT, WINDOWPLACEMENT, LPCSCROLLINFO, LPCMENUINFO, PGESTURECONFIG, DISPLAYCONFIG_PATH_INFO, LPINPUT, PCRAWINPUTDEVICE, LPCGUID, LPDRAWTEXTPARAMS, PAINTSTRUCT, LPCRECT, TOUCH_HIT_TESTING_PROXIMITY_EVALUATION, TOUCH_HIT_TESTING_INPUT, PFLASHWINFO, PALTTABINFO, WNDCLASSA, WNDCLASSEXA, WNDCLASSEXW, WNDCLASSW, MSGBOXPARAMSA, MSGBOXPARAMSW, POINTER_TOUCH_INFO, POINTER_TYPE_INFO, PWINDOWINFO, PTITLEBARINFO, PTOUCHINPUT, LPSCROLLINFO, PSCROLLBARINFO, PRAWINPUTDEVICE, POINTER_DEVICE_PROPERTY, PRAWINPUTDEVICELIST, POINTER_PEN_INFO, POINTER_INFO, INPUT_TRANSFORM, POINTER_DEVICE_INFO, LPMOUSEMOVEPOINT, LPMONITORINFO, LPMENUITEMINFOA, LPMENUITEMINFOW, LPMENUINFO, LPWNDCLASSA, LPWNDCLASSEXA, LPWNDCLASSEXW, LPWNDCLASSW, INPUT_MESSAGE_SOURCE, PCOMBOBOXINFO, PCURSORINFO, PGUITHREADINFO, PICONINFOEXA, PICONINFOEXW, PLASTINPUTINFO, PMENUBARINFO, POINTER_DEVICE_CURSOR_INFO } from "./win_user_struct";
import { DPI_AWARENESS_CONTEXT, WNDPROC, HGESTUREINFO, HTOUCHINPUT, DLGPROC, DESKTOPENUMPROCA, DESKTOPENUMPROCW, WNDENUMPROC, MONITORENUMPROC, PROPENUMPROCA, PROPENUMPROCEXA, PROPENUMPROCEXW, PROPENUMPROCW, WINSTAENUMPROCA, WINSTAENUMPROCW, HDEVNOTIFY, HWINEVENTHOOK, HSYNTHETICPOINTERDEVICE, POINTER_INPUT_TYPE, POINTER_FEEDBACK_MODE, DRAWSTATEPROC, PAR_STATE, DPI_AWARENESS, DIALOG_CONTROL_DPI_CHANGE_BEHAVIORS, DIALOG_DPI_CHANGE_BEHAVIORS, ORIENTATION_PREFERENCE, HMONITOR, HRAWINPUT, DPI_HOSTING_BEHAVIOR, FEEDBACK_TYPE, GRAYSTRINGPROC, MENUTEMPLATEA, MENUTEMPLATEW, DISPLAYCONFIG_MODE_INFO, DISPLAYCONFIG_TOPOLOGY_ID, HPOWERNOTIFY, SENDASYNCPROC, TIMERPROC, WINEVENTPROC } from "./win_user_type";
import { LPSECURITY_ATTRIBUTES } from "./win_base";
import { DISPLAYCONFIG_DEVICE_INFO_HEADER, PDISPLAY_DEVICEA, PDISPLAY_DEVICEW, BLENDFUNCTION } from "./win_gdi";
import { HKL, UINT, BOOL, DWORD, HWND, HMENU, HDWP, INT, HDC, LPDWORD, WPARAM, LPARAM, SIZE, LRESULT, WORD, HHOOK, LPVOID, HCURSOR, HICON, HACCEL, HWINSTA, HDESK, HBITMAP, HINSTANCE, ULONG, BYTE, PBYTE, HBRUSH, HRGN, PUINT, COLORREF, LPINT, PULONG, ATOM, LPBYTE, HOOKPROC, HMODULE, LPWORD, POINT } from "./win_def";
import { UINT_PTR, INT_PTR, UINT32, ULONG_PTR, LONG_PTR, PDWORD_PTR } from "./base_tsd";
import { LPCWSTR, LPCSTR, LONG, LPSTR, LPWSTR, VOID, HANDLE, ACCESS_MASK, PVOID, SHORT, PSECURITY_INFORMATION, PSECURITY_DESCRIPTOR, CHAR, WCHAR } from "./win_nt";

export const winUserFns = {
	ActivateKeyboardLayout: [HKL, [HKL, UINT]],
	AddClipboardFormatListener: [BOOL, [HWND]],
	AdjustWindowRect: [BOOL, [LPRECT, DWORD, BOOL]],
	AdjustWindowRectEx: [BOOL, [LPRECT, DWORD, BOOL, DWORD]],
	AdjustWindowRectExForDpi: [BOOL, [LPRECT, DWORD, BOOL, DWORD, UINT]],
	AllowSetForegroundWindow: [BOOL, [DWORD]],
	AnimateWindow: [BOOL, [HWND, DWORD, DWORD]],
	AnyPopup: [BOOL, []],
	AppendMenuA: [BOOL, [HMENU, UINT, UINT_PTR, LPCSTR]],
	AppendMenuW: [BOOL, [HMENU, UINT, UINT_PTR, LPCWSTR]],
	AreDpiAwarenessContextsEqual: [BOOL, [DPI_AWARENESS_CONTEXT, DPI_AWARENESS_CONTEXT]],
	ArrangeIconicWindows: [UINT, [HWND]],
	AttachThreadInput: [BOOL, [DWORD, DWORD, BOOL]],
	BeginDeferWindowPos: [HDWP, [INT]],
	BeginPaint: [HDC, [HWND, LPPAINTSTRUCT]],
	BlockInput: [BOOL, [BOOL]],
	BringWindowToTop: [BOOL, [HWND]],
	BroadcastSystemMessage: [LONG, [DWORD, LPDWORD, UINT, WPARAM, LPARAM]],
	BroadcastSystemMessageExA: [LONG, [DWORD, LPDWORD, UINT, WPARAM, LPARAM, PBSMINFO]],
	BroadcastSystemMessageExW: [LONG, [DWORD, LPDWORD, UINT, WPARAM, LPARAM, PBSMINFO]],
	BroadcastSystemMessageW: [LONG, [DWORD, LPDWORD, UINT, WPARAM, LPARAM]],
	CalculatePopupWindowPosition: [BOOL, [POINT, SIZE, UINT, RECT, RECT]],
	CallMsgFilterA: [BOOL, [LPMSG, INT]],
	CallMsgFilterW: [BOOL, [LPMSG, INT]],
	CallNextHookEx: [LRESULT, [HHOOK, INT, WPARAM, LPARAM]],
	CallWindowProcA: [LRESULT, [WNDPROC, HWND, UINT, WPARAM, LPARAM]],
	CallWindowProcW: [LRESULT, [WNDPROC, HWND, UINT, WPARAM, LPARAM]],
	CascadeWindows: [WORD, [HWND, UINT, RECT, UINT, HWND]],
	ChangeClipboardChain: [BOOL, [HWND, HWND]],
	ChangeDisplaySettingsA: [LONG, [DEVMODEA, DWORD]],
	ChangeDisplaySettingsExA: [LONG, [LPCSTR, DEVMODEA, HWND, DWORD, LPVOID]],
	ChangeDisplaySettingsExW: [LONG, [LPCWSTR, DEVMODEW, HWND, DWORD, LPVOID]],
	ChangeDisplaySettingsW: [LONG, [DEVMODEW, DWORD]],
	ChangeWindowMessageFilter: [BOOL, [UINT, DWORD]],
	ChangeWindowMessageFilterEx: [BOOL, [HWND, UINT, DWORD, PCHANGEFILTERSTRUCT]],
	CharLowerA: [LPSTR, [LPSTR]],
	CharLowerBuffA: [DWORD, [LPSTR, DWORD]],
	CharLowerBuffW: [DWORD, [LPWSTR, DWORD]],
	CharLowerW: [LPWSTR, [LPWSTR]],
	CharNextA: [LPSTR, [LPCSTR]],
	CharNextExA: [LPSTR, [WORD, LPCSTR, DWORD]],
	CharNextW: [LPWSTR, [LPCWSTR]],
	CharPrevA: [LPSTR, [LPCSTR, LPCSTR]],
	CharPrevExA: [LPSTR, [WORD, LPCSTR, LPCSTR, DWORD]],
	CharPrevW: [LPWSTR, [LPCWSTR, LPCWSTR]],
	CharToOemA: [BOOL, [LPCSTR, LPSTR]],
	CharToOemBuffA: [BOOL, [LPCSTR, LPSTR, DWORD]],
	CharToOemBuffW: [BOOL, [LPCWSTR, LPSTR, DWORD]],
	CharToOemW: [BOOL, [LPCWSTR, LPSTR]],
	CharUpperA: [LPSTR, [LPSTR]],
	CharUpperBuffA: [DWORD, [LPSTR, DWORD]],
	CharUpperBuffW: [DWORD, [LPWSTR, DWORD]],
	CharUpperW: [LPWSTR, [LPWSTR]],
	CheckDlgButton: [BOOL, [HWND, INT, UINT]],
	CheckMenuItem: [DWORD, [HMENU, UINT, UINT]],
	CheckMenuRadioItem: [BOOL, [HMENU, UINT, UINT, UINT, UINT]],
	CheckRadioButton: [BOOL, [HWND, INT, INT, INT]],
	ChildWindowFromPoint: [HWND, [HWND, POINT]],
	ChildWindowFromPointEx: [HWND, [HWND, POINT, UINT]],
	ClientToScreen: [BOOL, [HWND, LPPOINT]],
	ClipCursor: [BOOL, [RECT]],
	CloseClipboard: [BOOL, []],
	CloseDesktop: [BOOL, [HDESK]],
	CloseGestureInfoHandle: [BOOL, [HGESTUREINFO]],
	CloseTouchInputHandle: [BOOL, [HTOUCHINPUT]],
	CloseWindow: [BOOL, [HWND]],
	CloseWindowStation: [BOOL, [HWINSTA]],
	CopyAcceleratorTableA: [INT, [HACCEL, LPACCEL, INT]],
	CopyAcceleratorTableW: [INT, [HACCEL, LPACCEL, INT]],
	/**
	 *		#define CopyCursor(pcur) ((HCURSOR)CopyIcon((HICON)(pcur)))
	 */
	// CopyCursor: [VOID, [HCURSOR]],
	CopyIcon: [HICON, [HICON]],
	CopyImage: [HANDLE, [HANDLE, UINT, INT, INT, UINT]],
	CopyRect: [BOOL, [LPRECT, RECT]],
	CountClipboardFormats: [INT, []],
	CreateAcceleratorTableA: [HACCEL, [LPACCEL, INT]],
	CreateAcceleratorTableW: [HACCEL, [LPACCEL, INT]],
	CreateCaret: [BOOL, [HWND, HBITMAP, INT, INT]],
	CreateCursor: [HCURSOR, [HINSTANCE, INT, INT, INT, INT, VOID, VOID]],
	CreateDesktopA: [HDESK, [LPCSTR, LPCSTR, DEVMODEA, DWORD, ACCESS_MASK, LPSECURITY_ATTRIBUTES]],
	CreateDesktopExA: [HDESK, [LPCSTR, LPCSTR, DEVMODEA, DWORD, ACCESS_MASK, LPSECURITY_ATTRIBUTES, ULONG, PVOID]],
	CreateDesktopExW: [HDESK, [LPCWSTR, LPCWSTR, DEVMODEW, DWORD, ACCESS_MASK, LPSECURITY_ATTRIBUTES, ULONG, PVOID]],
	CreateDesktopW: [HDESK, [LPCWSTR, LPCWSTR, DEVMODEW, DWORD, ACCESS_MASK, LPSECURITY_ATTRIBUTES]],
	/**
	 *				#define CreateDialogA(hInstance, lpName, hWndParent, lpDialogFunc) \ CreateDialogParamA(hInstance, lpName, hWndParent, lpDialogFunc, 0L)
	 */
	// CreateDialogA: [VOID, [HINSTANCE, LPCTSTR, HWND, DLGPROC]],
	/**
	 *				#define CreateDialogIndirectA(hInstance, lpTemplate, hWndParent, lpDialogFunc) \ CreateDialogIndirectParamA(hInstance, lpTemplate, hWndParent, lpDialogFunc, 0L)
	 */
	// CreateDialogIndirectA: [VOID, [HINSTANCE, LPCDLGTEMPLATE, HWND, DLGPROC]],
	CreateDialogIndirectParamA: [HWND, [HINSTANCE, LPCDLGTEMPLATEA, HWND, DLGPROC, LPARAM]],
	CreateDialogIndirectParamW: [HWND, [HINSTANCE, LPCDLGTEMPLATEW, HWND, DLGPROC, LPARAM]],
	/**
	 *				#define CreateDialogIndirectW(hInstance, lpTemplate, hWndParent, lpDialogFunc) \ CreateDialogIndirectParamW(hInstance, lpTemplate, hWndParent, lpDialogFunc, 0L)
	 */
	// CreateDialogIndirectW: [VOID, [HINSTANCE, LPCDLGTEMPLATE, HWND, DLGPROC]],
	CreateDialogParamA: [HWND, [HINSTANCE, LPCSTR, HWND, DLGPROC, LPARAM]],
	CreateDialogParamW: [HWND, [HINSTANCE, LPCWSTR, HWND, DLGPROC, LPARAM]],
	/**
	 *			#define CreateDialogW(hInstance, lpName, hWndParent, lpDialogFunc) \ CreateDialogParamW(hInstance, lpName, hWndParent, lpDialogFunc, 0L)
	 */
	// CreateDialogW: [VOID, [HINSTANCE, LPCTSTR, HWND, DLGPROC]],
	CreateIcon: [HICON, [HINSTANCE, INT, INT, BYTE, BYTE, BYTE, BYTE]],
	CreateIconFromResource: [HICON, [PBYTE, DWORD, BOOL, DWORD]],
	CreateIconFromResourceEx: [HICON, [PBYTE, DWORD, BOOL, DWORD, INT, INT, UINT]],
	CreateIconIndirect: [HICON, [PICONINFO]],
	CreateMDIWindowA: [HWND, [LPCSTR, LPCSTR, DWORD, INT, INT, INT, INT, HWND, HINSTANCE, LPARAM]],
	CreateMDIWindowW: [HWND, [LPCWSTR, LPCWSTR, DWORD, INT, INT, INT, INT, HWND, HINSTANCE, LPARAM]],
	CreateMenu: [HMENU, []],
	CreatePopupMenu: [HMENU, []],
	//
	CreateSyntheticPointerDevice: [HSYNTHETICPOINTERDEVICE, [POINTER_INPUT_TYPE, ULONG, POINTER_FEEDBACK_MODE]],
	// CreateWindowA: [VOID, [LPCTSTR, LPCTSTR, DWORD, INT, INT, INT, INT, HWND, HMENU, HINSTANCE, LPVOID]],
	CreateWindowExA: [HWND, [DWORD, LPCSTR, LPCSTR, DWORD, INT, INT, INT, INT, HWND, HMENU, HINSTANCE, LPVOID]],
	CreateWindowExW: [HWND, [DWORD, LPCWSTR, LPCWSTR, DWORD, INT, INT, INT, INT, HWND, HMENU, HINSTANCE, LPVOID]],
	CreateWindowStationA: [HWINSTA, [LPCSTR, DWORD, ACCESS_MASK, LPSECURITY_ATTRIBUTES]],
	CreateWindowStationW: [HWINSTA, [LPCWSTR, DWORD, ACCESS_MASK, LPSECURITY_ATTRIBUTES]],
	// CreateWindowW: [VOID, [LPCTSTR, LPCTSTR, DWORD, INT, INT, INT, INT, HWND, HMENU, HINSTANCE, LPVOID]],
	DefDlgProcW: [/* LRESULT  */LRESULT, [HWND, UINT, WPARAM, LPARAM]],
	DeferWindowPos: [HDWP, [HDWP, HWND, HWND, INT, INT, INT, INT, UINT]],
	DefFrameProcA: [LRESULT, [HWND, HWND, UINT, WPARAM, LPARAM]],
	DefFrameProcW: [LRESULT, [HWND, HWND, UINT, WPARAM, LPARAM]],
	DefMDIChildProcA: [/* LRESULT  */LRESULT, [HWND, UINT, WPARAM, LPARAM]],
	DefMDIChildProcW: [/* LRESULT  */LRESULT, [HWND, UINT, WPARAM, LPARAM]],
	DefRawInputProc: [LRESULT, [PRAWINPUT, INT, UINT]],
	DefWindowProcA: [/* LRESULT  */LRESULT, [HWND, UINT, WPARAM, LPARAM]],
	DefWindowProcW: [/* LRESULT  */LRESULT, [HWND, UINT, WPARAM, LPARAM]],
	DeleteMenu: [BOOL, [HMENU, UINT, UINT]],
	DeregisterShellHookWindow: [BOOL, [HWND]],
	DestroyAcceleratorTable: [BOOL, [HACCEL]],
	//
	DestroyCaret: [BOOL, []],
	DestroyCursor: [BOOL, [HCURSOR]],
	DestroyIcon: [BOOL, [HICON]],
	DestroyMenu: [BOOL, [HMENU]],
	DestroySyntheticPointerDevice: [VOID, [HSYNTHETICPOINTERDEVICE]],
	DestroyWindow: [BOOL, [HWND]],
	// DialogBoxA: [VOID, [HINSTANCE, LPCTSTR, HWND, DLGPROC]],
	// DialogBoxIndirectA: [VOID, [HINSTANCE, LPCDLGTEMPLATE, HWND, DLGPROC]],
	DialogBoxIndirectParamA: [INT_PTR, [HINSTANCE, LPCDLGTEMPLATEA, HWND, DLGPROC, LPARAM]],
	DialogBoxIndirectParamW: [INT_PTR, [HINSTANCE, LPCDLGTEMPLATEW, HWND, DLGPROC, LPARAM]],
	// DialogBoxIndirectW: [VOID, [HINSTANCE, LPCDLGTEMPLATE, HWND, DLGPROC]],
	DialogBoxParamA: [INT_PTR, [HINSTANCE, LPCSTR, HWND, DLGPROC, LPARAM]],
	DialogBoxParamW: [INT_PTR, [HINSTANCE, LPCWSTR, HWND, DLGPROC, LPARAM]],
	// DialogBoxW: [VOID, [HINSTANCE, LPCTSTR, HWND, DLGPROC]],
	DisableProcessWindowsGhosting: [VOID, []],
	// DispatchMessage: [LRESULT, [MSG]],
	DispatchMessageA: [LRESULT, [MSG]],
	DispatchMessageW: [LRESULT, [MSG]],
	DisplayConfigGetDeviceInfo: [LONG, [DISPLAYCONFIG_DEVICE_INFO_HEADER]],
	DisplayConfigSetDeviceInfo: [LONG, [DISPLAYCONFIG_DEVICE_INFO_HEADER]],
	DlgDirListA: [INT, [HWND, LPSTR, INT, INT, UINT]],
	DlgDirListComboBoxA: [INT, [HWND, LPSTR, INT, INT, UINT]],
	DlgDirListComboBoxW: [INT, [HWND, LPWSTR, INT, INT, UINT]],
	DlgDirListW: [INT, [HWND, LPWSTR, INT, INT, UINT]],
	DlgDirSelectComboBoxExA: [BOOL, [HWND, LPSTR, INT, INT]],
	DlgDirSelectComboBoxExW: [BOOL, [HWND, LPWSTR, INT, INT]],
	DlgDirSelectExA: [BOOL, [HWND, LPSTR, INT, INT]],
	DlgDirSelectExW: [BOOL, [HWND, LPWSTR, INT, INT]],
	DragDetect: [BOOL, [HWND, POINT]],
	DrawAnimatedRects: [BOOL, [HWND, INT, RECT, RECT]],
	DrawCaption: [BOOL, [HWND, HDC, RECT, UINT]],
	DrawEdge: [BOOL, [HDC, LPRECT, UINT, UINT]],
	DrawFocusRect: [BOOL, [HDC, RECT]],
	DrawFrameControl: [BOOL, [HDC, LPRECT, UINT, UINT]],
	DrawIcon: [BOOL, [HDC, INT, INT, HICON]],
	DrawIconEx: [BOOL, [HDC, INT, INT, HICON, INT, INT, UINT, HBRUSH, UINT]],
	DrawMenuBar: [BOOL, [HWND]],
	DrawStateA: [BOOL, [HDC, HBRUSH, DRAWSTATEPROC, LPARAM, WPARAM, INT, INT, INT, INT, UINT]],
	DrawStateW: [BOOL, [HDC, HBRUSH, DRAWSTATEPROC, LPARAM, WPARAM, INT, INT, INT, INT, UINT]],
	// DrawText: [INT, [HDC, LPCTSTR, INT, LPRECT, UINT]],
	DrawTextA: [INT, [HDC, LPCSTR, INT, LPRECT, UINT]],
	DrawTextExA: [INT, [HDC, LPSTR, INT, LPRECT, UINT, LPDRAWTEXTPARAMS]],
	DrawTextExW: [INT, [HDC, LPWSTR, INT, LPRECT, UINT, LPDRAWTEXTPARAMS]],
	DrawTextW: [INT, [HDC, LPCWSTR, INT, LPRECT, UINT]],
	EmptyClipboard: [BOOL, []],
	EnableMenuItem: [BOOL, [HMENU, UINT, UINT]],
	EnableMouseInPointer: [BOOL, [BOOL]],
	EnableNonClientDpiScaling: [BOOL, [HWND]],
	EnableScrollBar: [BOOL, [HWND, UINT, UINT]],
	EnableWindow: [BOOL, [HWND, BOOL]],
	EndDeferWindowPos: [BOOL, [HDWP]],
	EndDialog: [BOOL, [HWND, INT_PTR]],
	EndMenu: [BOOL, []],
	EndPaint: [BOOL, [HWND, PAINTSTRUCT]],
	EndTask: [BOOL, [HWND, BOOL, BOOL]],
	EnumChildWindows: [BOOL, [HWND, WNDENUMPROC, LPARAM]],
	EnumClipboardFormats: [UINT, [UINT]],
	EnumDesktopsA: [BOOL, [HWINSTA, DESKTOPENUMPROCA, LPARAM]],
	EnumDesktopsW: [BOOL, [HWINSTA, DESKTOPENUMPROCW, LPARAM]],
	EnumDesktopWindows: [BOOL, [HDESK, WNDENUMPROC, LPARAM]],
	EnumDisplayDevicesA: [BOOL, [LPCSTR, DWORD, PDISPLAY_DEVICEA, DWORD]],
	EnumDisplayDevicesW: [BOOL, [LPCWSTR, DWORD, PDISPLAY_DEVICEW, DWORD]],
	EnumDisplayMonitors: [BOOL, [HDC, LPCRECT, MONITORENUMPROC, LPARAM]],
	EnumDisplaySettingsA: [BOOL, [LPCSTR, DWORD, DEVMODEA]],
	EnumDisplaySettingsExA: [BOOL, [LPCSTR, DWORD, DEVMODEA, DWORD]],
	EnumDisplaySettingsExW: [BOOL, [LPCWSTR, DWORD, DEVMODEW, DWORD]],
	EnumDisplaySettingsW: [BOOL, [LPCWSTR, DWORD, DEVMODEW]],
	EnumPropsA: [INT, [HWND, PROPENUMPROCA]],
	EnumPropsExA: [INT, [HWND, PROPENUMPROCEXA, LPARAM]],
	EnumPropsExW: [INT, [HWND, PROPENUMPROCEXW, LPARAM]],
	EnumPropsW: [INT, [HWND, PROPENUMPROCW]],
	EnumThreadWindows: [BOOL, [DWORD, WNDENUMPROC, LPARAM]],
	EnumWindows: [BOOL, [WNDENUMPROC, LPARAM]],
	EnumWindowStationsA: [BOOL, [WINSTAENUMPROCA, LPARAM]],
	EnumWindowStationsW: [BOOL, [WINSTAENUMPROCW, LPARAM]],
	EqualRect: [BOOL, [RECT, RECT]],
	EvaluateProximityToPolygon: [BOOL, [UINT32, POINT, TOUCH_HIT_TESTING_INPUT, TOUCH_HIT_TESTING_PROXIMITY_EVALUATION]],
	EvaluateProximityToRect: [BOOL, [RECT, TOUCH_HIT_TESTING_INPUT, TOUCH_HIT_TESTING_PROXIMITY_EVALUATION]],
	ExcludeUpdateRgn: [INT, [HDC, HWND]],

	/**
	 *			first must be zero  second must be zero
	 * 			#define ExitWindows(dwReserved, Code) ExitWindowsEx(EWX_LOGOFF, 0xFFFFFFFF)
	 */
	// ExitWindows: [VOID, [INT, LONG]],
	ExitWindowsEx: [BOOL, [UINT, DWORD]],
	FillRect: [INT, [HDC, RECT, HBRUSH]],
	FindWindowA: [HWND, [LPCSTR, LPCSTR]],
	FindWindowExA: [HWND, [HWND, HWND, LPCSTR, LPCSTR]],
	FindWindowExW: [HWND, [HWND, HWND, LPCWSTR, LPCWSTR]],
	FindWindowW: [HWND, [LPCWSTR, LPCWSTR]],
	FlashWindow: [BOOL, [HWND, BOOL]],
	FlashWindowEx: [BOOL, [PFLASHWINFO]],
	// FrameRect: [INT, [HDC, RECT, HBRUSH]],
	// // GET_APPCOMMAND_LPARAM: [VOID, [\placeholder]],
	// // GET_DEVICE_LPARAM: [VOID, [\placeholder]],
	// // GET_FLAGS_LPARAM: [VOID, [\placeholder]],
	// // GET_KEYSTATE_LPARAM: [VOID, [\placeholder]],
	// // GET_KEYSTATE_WPARAM: [VOID, [\placeholder]],
	// // GET_NCHITTEST_WPARAM: [VOID, [\placeholder]],
	// // GET_POINTERID_WPARAM: [VOID, [\placeholder]],
	// // GET_RAWINPUT_CODE_WPARAM: [VOID, [\placeholder]],
	// // GET_WHEEL_DELTA_WPARAM: [VOID, [\placeholder]],
	// // GET_XBUTTON_WPARAM: [VOID, [\placeholder]],
	//
	GetActiveWindow: [HWND, []],
	GetAltTabInfoA: [BOOL, [HWND, INT, PALTTABINFO, LPSTR, UINT]],
	GetAltTabInfoW: [BOOL, [HWND, INT, PALTTABINFO, LPWSTR, UINT]],
	GetAncestor: [HWND, [HWND, UINT]],
	GetAsyncKeyState: [SHORT, [INT]],
	GetAutoRotationState: [BOOL, [PAR_STATE]],
	GetAwarenessFromDpiAwarenessContext: [DPI_AWARENESS, [DPI_AWARENESS_CONTEXT]],
	GetCapture: [HWND, []],
	GetCaretBlinkTime: [UINT, []],
	GetCaretPos: [BOOL, [LPPOINT]],
	GetCIMSSM: [BOOL, [INPUT_MESSAGE_SOURCE]],
	GetClassInfoA: [BOOL, [HINSTANCE, LPCSTR, LPWNDCLASSA]],
	GetClassInfoExA: [BOOL, [HINSTANCE, LPCSTR, LPWNDCLASSEXA]],
	GetClassInfoExW: [BOOL, [HINSTANCE, LPCWSTR, LPWNDCLASSEXW]],
	GetClassInfoW: [BOOL, [HINSTANCE, LPCWSTR, LPWNDCLASSW]],
	GetClassLongA: [DWORD, [HWND, INT]],
	GetClassLongPtrA: [ULONG_PTR, [HWND, INT]],
	GetClassLongPtrW: [ULONG_PTR, [HWND, INT]],
	GetClassLongW: [DWORD, [HWND, INT]],
	// GetClassName: [INT, [HWND, LPTSTR, INT]],
	GetClassNameA: [INT, [HWND, LPSTR, INT]],
	GetClassNameW: [INT, [HWND, LPWSTR, INT]],
	GetClassWord: [WORD, [HWND, INT]],
	GetClientRect: [BOOL, [HWND, LPRECT]],
	GetClipboardData: [HANDLE, [UINT]],
	GetClipboardFormatNameA: [INT, [UINT, LPSTR, INT]],
	GetClipboardFormatNameW: [INT, [UINT, LPWSTR, INT]],
	GetClipboardOwner: [HWND, []],
	GetClipboardSequenceNumber: [DWORD, []],
	GetClipboardViewer: [HWND, []],
	GetClipCursor: [BOOL, [LPRECT]],
	GetComboBoxInfo: [BOOL, [HWND, PCOMBOBOXINFO]],
	GetCurrentInputMessageSource: [BOOL, [INPUT_MESSAGE_SOURCE]],
	GetCursor: [HCURSOR, []],
	GetCursorInfo: [BOOL, [PCURSORINFO]],
	GetCursorPos: [BOOL, [LPPOINT]],
	GetDC: [HDC, [HWND]],
	GetDCEx: [HDC, [HWND, HRGN, DWORD]],
	GetDesktopWindow: [HWND, []],
	GetDialogBaseUnits: [LONG, []],
	GetDialogControlDpiChangeBehavior: [DIALOG_CONTROL_DPI_CHANGE_BEHAVIORS, [HWND]],
	GetDialogDpiChangeBehavior: [DIALOG_DPI_CHANGE_BEHAVIORS, [HWND]],
	GetDisplayAutoRotationPreferences: [BOOL, [ORIENTATION_PREFERENCE]],
	// GetDisplayAutoRotationPreferencesByProcessId: [BOOL, [DWORD, ORIENTATION_PREFERENCE, PBOOL]],
	GetDisplayConfigBufferSizes: [LONG, [UINT32, UINT32, UINT32]],
	GetDlgCtrlID: [INT, [HWND]],
	GetDlgItem: [HWND, [HWND, INT]],
	GetDlgItemInt: [UINT, [HWND, INT, BOOL, BOOL]],
	GetDlgItemTextA: [UINT, [HWND, INT, LPSTR, INT]],
	GetDlgItemTextW: [UINT, [HWND, INT, LPWSTR, INT]],
	GetDoubleClickTime: [UINT, []],
	GetDpiForSystem: [UINT, []],
	GetDpiForWindow: [UINT, [HWND]],
	GetDpiFromDpiAwarenessContext: [UINT, [DPI_AWARENESS_CONTEXT]],
	GetFocus: [HWND, []],
	GetForegroundWindow: [HWND, []],
	GetGestureConfig: [BOOL, [HWND, DWORD, DWORD, PUINT, PGESTURECONFIG, UINT]],
	GetGestureExtraArgs: [BOOL, [HGESTUREINFO, UINT, PBYTE]],
	GetGestureInfo: [BOOL, [HGESTUREINFO, PGESTUREINFO]],
	GetGuiResources: [DWORD, [HANDLE, DWORD]],
	GetGUIThreadInfo: [BOOL, [DWORD, PGUITHREADINFO]],
	GetIconInfo: [BOOL, [HICON, PICONINFO]],
	GetIconInfoExA: [BOOL, [HICON, PICONINFOEXA]],
	GetIconInfoExW: [BOOL, [HICON, PICONINFOEXW]],
	GetInputState: [BOOL, []],
	GetKBCodePage: [UINT, []],
	GetKeyboardLayout: [HKL, [DWORD]],
	GetKeyboardLayoutList: [INT, [INT, HKL]],
	GetKeyboardLayoutNameA: [BOOL, [LPSTR]],
	GetKeyboardLayoutNameW: [BOOL, [LPWSTR]],
	GetKeyboardState: [BOOL, [PBYTE]],
	GetKeyboardType: [INT, [INT]],
	GetKeyNameTextA: [INT, [LONG, LPSTR, INT]],
	GetKeyNameTextW: [INT, [LONG, LPWSTR, INT]],
	GetKeyState: [SHORT, [INT]],
	GetLastActivePopup: [HWND, [HWND]],
	GetLastInputInfo: [BOOL, [PLASTINPUTINFO]],
	GetLayeredWindowAttributes: [BOOL, [HWND, COLORREF, BYTE, DWORD]],
	GetListBoxInfo: [DWORD, [HWND]],
	GetMenu: [HMENU, [HWND]],
	//
	GetMenuBarInfo: [BOOL, [HWND, LONG, LONG, PMENUBARINFO]],
	GetMenuCheckMarkDimensions: [LONG, []],
	GetMenuContextHelpId: [DWORD, [HMENU]],
	GetMenuDefaultItem: [UINT, [HMENU, UINT, UINT]],
	GetMenuInfo: [BOOL, [HMENU, LPMENUINFO]],
	GetMenuItemCount: [INT, [HMENU]],
	GetMenuItemID: [UINT, [HMENU, INT]],
	GetMenuItemInfoA: [BOOL, [HMENU, UINT, BOOL, LPMENUITEMINFOA]],
	GetMenuItemInfoW: [BOOL, [HMENU, UINT, BOOL, LPMENUITEMINFOW]],
	GetMenuItemRect: [BOOL, [HWND, HMENU, UINT, LPRECT]],
	GetMenuState: [UINT, [HMENU, UINT, UINT]],
	GetMenuStringA: [INT, [HMENU, UINT, LPSTR, INT, UINT]],
	GetMenuStringW: [INT, [HMENU, UINT, LPWSTR, INT, UINT]],
	// GetMessage: [BOOL, [LPMSG, HWND, UINT, UINT]],
	GetMessageA: [BOOL, [LPMSG, HWND, UINT, UINT]],
	GetMessageExtraInfo: [LPARAM, []],
	GetMessagePos: [DWORD, []],
	GetMessageTime: [LONG, []],
	GetMessageW: [BOOL, [LPMSG, HWND, UINT, UINT]],
	GetMonitorInfoA: [BOOL, [HMONITOR, LPMONITORINFO]],
	GetMonitorInfoW: [BOOL, [HMONITOR, LPMONITORINFO]],
	GetMouseMovePointsEx: [INT, [UINT, LPMOUSEMOVEPOINT, LPMOUSEMOVEPOINT, INT, DWORD]],
	GetNextDlgGroupItem: [HWND, [HWND, HWND, BOOL]],
	GetNextDlgTabItem: [HWND, [HWND, HWND, BOOL]],
	// /**
	//  * #define GetNextWindow(hWnd, wCmd) GetWindow(hWnd, wCmd)
	//  */
	// GetNextWindow: [VOID, []],
	GetOpenClipboardWindow: [HWND, []],
	GetParent: [HWND, [HWND]],
	GetPhysicalCursorPos: [BOOL, [LPPOINT]],
	GetPointerCursorId: [BOOL, [UINT32, UINT32]],
	GetPointerDevice: [BOOL, [HANDLE, POINTER_DEVICE_INFO]],
	GetPointerDeviceCursors: [BOOL, [HANDLE, UINT32, POINTER_DEVICE_CURSOR_INFO]],
	GetPointerDeviceProperties: [BOOL, [HANDLE, UINT32, POINTER_DEVICE_PROPERTY]],
	GetPointerDeviceRects: [BOOL, [HANDLE, RECT, RECT]],
	GetPointerDevices: [BOOL, [UINT32, POINTER_DEVICE_INFO]],
	GetPointerFrameInfo: [BOOL, [UINT32, UINT32, POINTER_INFO]],
	GetPointerFrameInfoHistory: [BOOL, [UINT32, UINT32, UINT32, POINTER_INFO]],
	GetPointerFramePenInfo: [BOOL, [UINT32, UINT32, POINTER_PEN_INFO]],
	GetPointerFramePenInfoHistory: [BOOL, [UINT32, UINT32, UINT32, POINTER_PEN_INFO]],
	GetPointerFrameTouchInfo: [BOOL, [UINT32, UINT32, POINTER_TOUCH_INFO]],
	GetPointerFrameTouchInfoHistory: [BOOL, [UINT32, UINT32, UINT32, POINTER_TOUCH_INFO]],
	GetPointerInfo: [BOOL, [UINT32, POINTER_INFO]],
	GetPointerInfoHistory: [BOOL, [UINT32, UINT32, POINTER_INFO]],
	GetPointerInputTransform: [BOOL, [UINT32, UINT32, INPUT_TRANSFORM]],
	GetPointerPenInfo: [BOOL, [UINT32, POINTER_PEN_INFO]],
	GetPointerPenInfoHistory: [BOOL, [UINT32, UINT32, POINTER_PEN_INFO]],
	GetPointerTouchInfo: [BOOL, [UINT32, POINTER_TOUCH_INFO]],
	GetPointerTouchInfoHistory: [BOOL, [UINT32, UINT32, POINTER_TOUCH_INFO]],
	GetPointerType: [BOOL, [UINT32, POINTER_INPUT_TYPE]],
	GetPriorityClipboardFormat: [INT, [UINT, INT]],
	GetProcessDefaultLayout: [BOOL, [DWORD]],
	GetProcessWindowStation: [HWINSTA, []],
	GetPropA: [HANDLE, [HWND, LPCSTR]],
	GetPropW: [HANDLE, [HWND, LPCWSTR]],
	GetQueueStatus: [DWORD, [UINT]],
	GetRawInputBuffer: [UINT, [PRAWINPUT, PUINT, UINT]],
	GetRawInputData: [UINT, [HRAWINPUT, UINT, LPVOID, PUINT, UINT]],
	GetRawInputDeviceInfoA: [UINT, [HANDLE, UINT, LPVOID, PUINT]],
	GetRawInputDeviceInfoW: [UINT, [HANDLE, UINT, LPVOID, PUINT]],
	GetRawInputDeviceList: [UINT, [PRAWINPUTDEVICELIST, PUINT, UINT]],
	GetRawPointerDeviceData: [BOOL, [UINT32, UINT32, UINT32, POINTER_DEVICE_PROPERTY, LONG]],
	GetRegisteredRawInputDevices: [UINT, [PRAWINPUTDEVICE, PUINT, UINT]],
	GetScrollBarInfo: [BOOL, [HWND, LONG, PSCROLLBARINFO]],
	GetScrollInfo: [BOOL, [HWND, INT, LPSCROLLINFO]],
	GetScrollPos: [INT, [HWND, INT]],
	GetScrollRange: [BOOL, [HWND, INT, LPINT, LPINT]],
	GetShellWindow: [HWND, []],
	GetSubMenu: [HMENU, [HMENU, INT]],
	GetSysColor: [DWORD, [INT]],
	GetSysColorBrush: [HBRUSH, [INT]],
	GetSystemDpiForProcess: [UINT, [HANDLE]],
	GetSystemMenu: [HMENU, [HWND, BOOL]],
	GetSystemMetrics: [INT, [INT]],
	GetSystemMetricsForDpi: [INT, [INT, UINT]],
	GetTabbedTextExtentA: [DWORD, [HDC, LPCSTR, INT, INT, INT]],
	GetTabbedTextExtentW: [DWORD, [HDC, LPCWSTR, INT, INT, INT]],
	GetThreadDesktop: [HDESK, [DWORD]],
	GetThreadDpiAwarenessContext: [DPI_AWARENESS_CONTEXT, []],
	GetThreadDpiHostingBehavior: [DPI_HOSTING_BEHAVIOR, []],
	GetTitleBarInfo: [BOOL, [HWND, PTITLEBARINFO]],
	GetTopWindow: [HWND, [HWND]],
	GetTouchInputInfo: [BOOL, [HTOUCHINPUT, UINT, PTOUCHINPUT, INT]],
	GetUnpredictedMessagePos: [DWORD, []],
	GetUpdatedClipboardFormats: [BOOL, [PUINT, UINT, PUINT]],
	GetUpdateRect: [BOOL, [HWND, LPRECT, BOOL]],
	GetUpdateRgn: [INT, [HWND, HRGN, BOOL]],
	GetUserObjectInformationA: [BOOL, [HANDLE, INT, PVOID, DWORD, LPDWORD]],
	GetUserObjectInformationW: [BOOL, [HANDLE, INT, PVOID, DWORD, LPDWORD]],
	GetUserObjectSecurity: [BOOL, [HANDLE, PSECURITY_INFORMATION, PSECURITY_DESCRIPTOR, DWORD, LPDWORD]],
	GetWindow: [HWND, [HWND, UINT]],
	GetWindowContextHelpId: [DWORD, [HWND]],
	GetWindowDC: [HDC, [HWND]],
	GetWindowDisplayAffinity: [BOOL, [HWND, DWORD]],
	GetWindowDpiAwarenessContext: [DPI_AWARENESS_CONTEXT, [HWND]],
	GetWindowDpiHostingBehavior: [DPI_HOSTING_BEHAVIOR, [HWND]],
	GetWindowFeedbackSetting: [BOOL, [HWND, FEEDBACK_TYPE, DWORD, UINT32, VOID]],
	GetWindowInfo: [BOOL, [HWND, PWINDOWINFO]],
	GetWindowLongA: [LONG, [HWND, INT]],
	GetWindowLongPtrA: [LONG_PTR, [HWND, INT]],
	GetWindowLongPtrW: [LONG_PTR, [HWND, INT]],
	GetWindowLongW: [LONG, [HWND, INT]],
	GetWindowModuleFileNameA: [UINT, [HWND, LPSTR, UINT]],
	GetWindowModuleFileNameW: [UINT, [HWND, LPWSTR, UINT]],
	GetWindowPlacement: [BOOL, [HWND, WINDOWPLACEMENT]],
	GetWindowRect: [BOOL, [HWND, LPRECT]],
	GetWindowRgn: [INT, [HWND, HRGN]],
	GetWindowRgnBox: [INT, [HWND, LPRECT]],
	GetWindowTextA: [INT, [HWND, LPSTR, INT]],
	GetWindowTextLengthA: [INT, [HWND]],
	GetWindowTextLengthW: [INT, [HWND]],
	GetWindowTextW: [INT, [HWND, LPWSTR, INT]],
	GetWindowThreadProcessId: [DWORD, [HWND, LPDWORD]],
	// // GID_ROTATE_ANGLE_FROM_ARGUMENT: [VOID, [\placeholder]],
	// // GID_ROTATE_ANGLE_TO_ARGUMENT: [VOID, [\placeholder]],
	GrayStringA: [BOOL, [HDC, HBRUSH, GRAYSTRINGPROC, LPARAM, INT, INT, INT, INT, INT]],
	GrayStringW: [BOOL, [HDC, HBRUSH, GRAYSTRINGPROC, LPARAM, INT, INT, INT, INT, INT]],
	// HAS_POINTER_CONFIDENCE_WPARAM: [VOID, [\placeholder]],
	HideCaret: [BOOL, [HWND]],
	HiliteMenuItem: [BOOL, [HWND, HMENU, UINT, UINT]],
	InflateRect: [BOOL, [LPRECT, INT, INT]],
	InitializeTouchInjection: [BOOL, [UINT32, DWORD]],
	InjectSyntheticPointerInput: [BOOL, [HSYNTHETICPOINTERDEVICE, POINTER_TYPE_INFO, UINT32]],
	InjectTouchInput: [BOOL, [UINT32, POINTER_TOUCH_INFO]],
	// // InSendMessage: [BOOL, [\placeholder]],
	InSendMessageEx: [DWORD, [LPVOID]],
	InsertMenuA: [BOOL, [HMENU, UINT, UINT, UINT_PTR, LPCSTR]],
	InsertMenuItemA: [BOOL, [HMENU, UINT, BOOL, LPCMENUITEMINFOA]],
	InsertMenuItemW: [BOOL, [HMENU, UINT, BOOL, LPCMENUITEMINFOW]],
	InsertMenuW: [BOOL, [HMENU, UINT, UINT, UINT_PTR, LPCWSTR]],
	InternalGetWindowText: [INT, [HWND, LPWSTR, INT]],
	IntersectRect: [BOOL, [LPRECT, RECT, RECT]],
	InvalidateRect: [BOOL, [HWND, RECT, BOOL]],
	InvalidateRgn: [BOOL, [HWND, HRGN, BOOL]],
	InvertRect: [BOOL, [HDC, RECT]],
	// // IS_INTRESOURCE: [VOID, [\placeholder]],
	// IS_POINTER_CANCELED_WPARAM: [VOID, [\placeholder]],
	// // IS_POINTER_FIFTHBUTTON_WPARAM: [VOID, [\placeholder]],
	// // IS_POINTER_FIRSTBUTTON_WPARAM: [VOID, [\placeholder]],
	// // IS_POINTER_FLAG_SET_WPARAM: [VOID, [\placeholder]],
	// // IS_POINTER_FOURTHBUTTON_WPARAM: [VOID, [\placeholder]],
	// // IS_POINTER_INCONTACT_WPARAM: [VOID, [\placeholder]],
	// // IS_POINTER_INRANGE_WPARAM: [VOID, [\placeholder]],
	// // IS_POINTER_NEW_WPARAM: [VOID, [\placeholder]],
	// // IS_POINTER_SECONDBUTTON_WPARAM: [VOID, [\placeholder]],
	// // IS_POINTER_THIRDBUTTON_WPARAM: [VOID, [\placeholder]],
	IsCharAlphaA: [BOOL, [CHAR]],
	IsCharAlphaNumericA: [BOOL, [CHAR]],
	IsCharAlphaNumericW: [BOOL, [WCHAR]],
	IsCharAlphaW: [BOOL, [WCHAR]],
	IsCharLowerA: [BOOL, [CHAR]],
	IsCharLowerW: [BOOL, [WCHAR]],
	IsCharUpperA: [BOOL, [CHAR]],
	IsCharUpperW: [BOOL, [WCHAR]],
	IsChild: [BOOL, [HWND, HWND]],
	IsClipboardFormatAvailable: [BOOL, [UINT]],
	IsDialogMessageA: [BOOL, [HWND, LPMSG]],
	IsDialogMessageW: [BOOL, [HWND, LPMSG]],
	IsDlgButtonChecked: [UINT, [HWND, INT]],
	IsGUIThread: [BOOL, [BOOL]],
	IsHungAppWindow: [BOOL, [HWND]],
	IsIconic: [BOOL, [HWND]],
	IsImmersiveProcess: [BOOL, [HANDLE]],
	IsMenu: [BOOL, [HMENU]],
	IsMouseInPointerEnabled: [BOOL, []],
	IsProcessDPIAware: [BOOL, []],
	IsRectEmpty: [BOOL, [RECT]],
	IsTouchWindow: [BOOL, [HWND, PULONG]],
	IsValidDpiAwarenessContext: [BOOL, [DPI_AWARENESS_CONTEXT]],
	IsWindow: [BOOL, [HWND]],
	IsWindowEnabled: [BOOL, [HWND]],
	IsWindowUnicode: [BOOL, [HWND]],
	IsWindowVisible: [BOOL, [HWND]],
	IsWinEventHookInstalled: [BOOL, [DWORD]],
	IsWow64Message: [BOOL, []],
	IsZoomed: [BOOL, [HWND]],
	keybd_event: [VOID, [BYTE, BYTE, DWORD, ULONG_PTR]],
	KillTimer: [BOOL, [HWND, UINT_PTR]],
	LoadAcceleratorsA: [HACCEL, [HINSTANCE, LPCSTR]],
	LoadAcceleratorsW: [HACCEL, [HINSTANCE, LPCWSTR]],
	LoadBitmapA: [HBITMAP, [HINSTANCE, LPCSTR]],
	LoadBitmapW: [HBITMAP, [HINSTANCE, LPCWSTR]],
	LoadCursorA: [HCURSOR, [HINSTANCE, LPCSTR]],
	LoadCursorFromFileA: [HCURSOR, [LPCSTR]],
	LoadCursorFromFileW: [HCURSOR, [LPCWSTR]],
	LoadCursorW: [HCURSOR, [HINSTANCE, LPCWSTR]],
	LoadIconA: [HICON, [HINSTANCE, LPCSTR]],
	LoadIconW: [HICON, [HINSTANCE, LPCWSTR]],
	LoadImageA: [HANDLE, [HINSTANCE, LPCSTR, UINT, INT, INT, UINT]],
	LoadImageW: [HANDLE, [HINSTANCE, LPCWSTR, UINT, INT, INT, UINT]],
	LoadKeyboardLayoutA: [HKL, [LPCSTR, UINT]],
	LoadKeyboardLayoutW: [HKL, [LPCWSTR, UINT]],
	LoadMenuA: [HMENU, [HINSTANCE, LPCSTR]],
	LoadMenuIndirectA: [HMENU, [MENUTEMPLATEA]],
	LoadMenuIndirectW: [HMENU, [MENUTEMPLATEW]],
	LoadMenuW: [HMENU, [HINSTANCE, LPCWSTR]],
	LoadStringA: [INT, [HINSTANCE, UINT, LPSTR, INT]],
	LoadStringW: [INT, [HINSTANCE, UINT, LPWSTR, INT]],
	LockSetForegroundWindow: [BOOL, [UINT]],
	LockWindowUpdate: [BOOL, [HWND]],
	LockWorkStation: [BOOL, []],
	LogicalToPhysicalPoint: [BOOL, [HWND, LPPOINT]],
	LogicalToPhysicalPointForPerMonitorDPI: [BOOL, [HWND, LPPOINT]],
	LookupIconIdFromDirectory: [INT, [PBYTE, BOOL]],
	LookupIconIdFromDirectoryEx: [INT, [PBYTE, BOOL, INT, INT, UINT]],
	// // MAKEINTRESOURCEA: [VOID, [\placeholder]],
	// // MAKEINTRESOURCEW: [VOID, [\placeholder]],
	// // MAKELPARAM: [VOID, ['int', 'int']]
	// // MAKELRESULT: [VOID, [\placeholder]],
	// // MAKEWPARAM: [VOID, [\placeholder]],
	MapDialogRect: [BOOL, [HWND, LPRECT]],
	MapVirtualKeyA: [UINT, [UINT, UINT]],
	MapVirtualKeyExA: [UINT, [UINT, UINT, HKL]],
	MapVirtualKeyExW: [UINT, [UINT, UINT, HKL]],
	MapVirtualKeyW: [UINT, [UINT, UINT]],
	MapWindowPoints: [INT, [HWND, HWND, LPPOINT, UINT]],
	MenuItemFromPoint: [INT, [HWND, HMENU, POINT]],
	MessageBeep: [BOOL, [UINT]],
	// MessageBox: [INT, [HWND, LPCTSTR, LPCTSTR, UINT]],
	MessageBoxA: [INT, [HWND, LPCSTR, LPCSTR, UINT]],
	MessageBoxExA: [INT, [HWND, LPCSTR, LPCSTR, UINT, WORD]],
	MessageBoxExW: [INT, [HWND, LPCWSTR, LPCWSTR, UINT, WORD]],
	MessageBoxIndirectA: [INT, [MSGBOXPARAMSA]],
	MessageBoxIndirectW: [INT, [MSGBOXPARAMSW]],
	MessageBoxW: [INT, [HWND, LPCWSTR, LPCWSTR, UINT]],
	ModifyMenuA: [BOOL, [HMENU, UINT, UINT, UINT_PTR, LPCSTR]],
	ModifyMenuW: [BOOL, [HMENU, UINT, UINT, UINT_PTR, LPCWSTR]],
	MonitorFromPoint: [HMONITOR, [POINT, DWORD]],
	MonitorFromRect: [HMONITOR, [LPCRECT, DWORD]],
	MonitorFromWindow: [HMONITOR, [HWND, DWORD]],
	mouse_event: [VOID, [DWORD, DWORD, DWORD, DWORD, ULONG_PTR]],
	MoveWindow: [BOOL, [HWND, INT, INT, INT, INT, BOOL]],
	MsgWaitForMultipleObjects: [DWORD, [DWORD, HANDLE, BOOL, DWORD, DWORD]],
	MsgWaitForMultipleObjectsEx: [DWORD, [DWORD, HANDLE, DWORD, DWORD, DWORD]],
	// NEXTRAWINPUTBLOCK: [VOID, ['pointer']],
	NotifyWinEvent: [VOID, [DWORD, HWND, LONG, LONG]],
	OemKeyScan: [DWORD, [WORD]],
	OemToCharA: [BOOL, [LPCSTR, LPSTR]],
	OemToCharBuffA: [BOOL, [LPCSTR, LPSTR, DWORD]],
	OemToCharBuffW: [BOOL, [LPCSTR, LPWSTR, DWORD]],
	OemToCharW: [BOOL, [LPCSTR, LPWSTR]],
	OffsetRect: [BOOL, [LPRECT, INT, INT]],
	OpenClipboard: [BOOL, [HWND]],
	OpenDesktopA: [HDESK, [LPCSTR, DWORD, BOOL, ACCESS_MASK]],
	OpenDesktopW: [HDESK, [LPCWSTR, DWORD, BOOL, ACCESS_MASK]],
	OpenIcon: [BOOL, [HWND]],
	OpenInputDesktop: [HDESK, [DWORD, BOOL, ACCESS_MASK]],
	OpenWindowStationA: [HWINSTA, [LPCSTR, BOOL, ACCESS_MASK]],
	OpenWindowStationW: [HWINSTA, [LPCWSTR, BOOL, ACCESS_MASK]],
	PackTouchHitTestingProximityEvaluation: [LRESULT, [TOUCH_HIT_TESTING_INPUT, TOUCH_HIT_TESTING_PROXIMITY_EVALUATION]],
	PaintDesktop: [BOOL, [HDC]],
	PeekMessageA: [BOOL, [LPMSG, HWND, UINT, UINT, UINT]],
	PeekMessageW: [BOOL, [LPMSG, HWND, UINT, UINT, UINT]],
	PhysicalToLogicalPoint: [BOOL, [HWND, LPPOINT]],
	PhysicalToLogicalPointForPerMonitorDPI: [BOOL, [HWND, LPPOINT]],
	// POINTSTOPOINT: [VOID, [\placeholder]],
	// POINTTOPOINTS: [VOID, [\placeholder]],
	PostMessageA: [BOOL, [HWND, UINT, WPARAM, LPARAM]],
	PostMessageW: [BOOL, [HWND, UINT, WPARAM, LPARAM]],
	PostQuitMessage: [VOID, [INT]],
	PostThreadMessageA: [BOOL, [DWORD, UINT, WPARAM, LPARAM]],
	PostThreadMessageW: [BOOL, [DWORD, UINT, WPARAM, LPARAM]],
	PrintWindow: [BOOL, [HWND, HDC, UINT]],
	PrivateExtractIconsA: [UINT, [LPCSTR, INT, INT, INT, HICON, UINT, UINT, UINT]],
	PrivateExtractIconsW: [UINT, [LPCWSTR, INT, INT, INT, HICON, UINT, UINT, UINT]],
	PtInRect: [BOOL, [RECT, POINT]],
	QueryDisplayConfig: [LONG, [UINT32, UINT32, DISPLAYCONFIG_PATH_INFO, UINT32, DISPLAYCONFIG_MODE_INFO, DISPLAYCONFIG_TOPOLOGY_ID]],
	RealChildWindowFromPoint: [HWND, [HWND, POINT]],
	RealGetWindowClassW: [UINT, [HWND, LPWSTR, UINT]],
	RedrawWindow: [BOOL, [HWND, RECT, HRGN, UINT]],
	//
	RegisterClassA: [ATOM, [WNDCLASSA]],
	RegisterClassExA: [ATOM, [WNDCLASSEXA]],
	RegisterClassExW: [ATOM, [WNDCLASSEXW]],
	RegisterClassW: [ATOM, [WNDCLASSW]],
	RegisterClipboardFormatA: [UINT, [LPCSTR]],
	RegisterClipboardFormatW: [UINT, [LPCWSTR]],
	RegisterDeviceNotificationA: [HDEVNOTIFY, [HANDLE, LPVOID, DWORD]],
	RegisterDeviceNotificationW: [HDEVNOTIFY, [HANDLE, LPVOID, DWORD]],
	RegisterHotKey: [BOOL, [HWND, INT, UINT, UINT]],
	RegisterPointerDeviceNotifications: [BOOL, [HWND, BOOL]],
	RegisterPointerInputTarget: [BOOL, [HWND, POINTER_INPUT_TYPE]],
	RegisterPointerInputTargetEx: [BOOL, [HWND, POINTER_INPUT_TYPE, BOOL]],
	RegisterPowerSettingNotification: [HPOWERNOTIFY, [HANDLE, LPCGUID, DWORD]],
	RegisterRawInputDevices: [BOOL, [PCRAWINPUTDEVICE, UINT, UINT]],
	RegisterShellHookWindow: [BOOL, [HWND]],
	RegisterSuspendResumeNotification: [HPOWERNOTIFY, [HANDLE, DWORD]],
	RegisterTouchHitTestingWindow: [BOOL, [HWND, ULONG]],
	RegisterTouchWindow: [BOOL, [HWND, ULONG]],
	RegisterWindowMessageA: [UINT, [LPCSTR]],
	RegisterWindowMessageW: [UINT, [LPCWSTR]],
	ReleaseCapture: [BOOL, []],
	ReleaseDC: [INT, [HWND, HDC]],
	RemoveClipboardFormatListener: [BOOL, [HWND]],
	RemoveMenu: [BOOL, [HMENU, UINT, UINT]],
	RemovePropA: [HANDLE, [HWND, LPCSTR]],
	RemovePropW: [HANDLE, [HWND, LPCWSTR]],
	ReplyMessage: [BOOL, [LRESULT]],
	ScreenToClient: [BOOL, [HWND, LPPOINT]],
	ScrollDC: [BOOL, [HDC, INT, INT, RECT, RECT, HRGN, LPRECT]],
	ScrollWindow: [BOOL, [HWND, INT, INT, RECT, RECT]],
	ScrollWindowEx: [INT, [HWND, INT, INT, RECT, RECT, HRGN, LPRECT, UINT]],
	SendDlgItemMessageA: [LRESULT, [HWND, INT, UINT, WPARAM, LPARAM]],
	SendDlgItemMessageW: [LRESULT, [HWND, INT, UINT, WPARAM, LPARAM]],
	SendInput: [UINT, [UINT, LPINPUT, INT]],
	/**
	 *				#define SendMessage  SendMessageW
	 */
	// SendMessage: [LRESULT, [HWND, UINT, WPARAM, LPARAM]],
	SendMessageA: [LRESULT, [HWND, UINT, WPARAM, LPARAM]],
	SendMessageCallbackA: [BOOL, [HWND, UINT, WPARAM, LPARAM, SENDASYNCPROC, ULONG_PTR]],
	SendMessageCallbackW: [BOOL, [HWND, UINT, WPARAM, LPARAM, SENDASYNCPROC, ULONG_PTR]],
	SendMessageTimeoutA: [LRESULT, [HWND, UINT, WPARAM, LPARAM, UINT, UINT, PDWORD_PTR]],
	SendMessageTimeoutW: [LRESULT, [HWND, UINT, WPARAM, LPARAM, UINT, UINT, PDWORD_PTR]],
	SendMessageW: [LRESULT, [HWND, UINT, WPARAM, LPARAM]],
	SendNotifyMessageA: [BOOL, [HWND, UINT, WPARAM, LPARAM]],
	SendNotifyMessageW: [BOOL, [HWND, UINT, WPARAM, LPARAM]],
	SetActiveWindow: [HWND, [HWND]],
	SetCapture: [HWND, [HWND]],
	SetCaretBlinkTime: [BOOL, [UINT]],
	SetCaretPos: [BOOL, [INT, INT]],
	SetClassLongA: [DWORD, [HWND, INT, LONG]],
	SetClassLongPtrA: [ULONG_PTR, [HWND, INT, LONG_PTR]],
	SetClassLongPtrW: [ULONG_PTR, [HWND, INT, LONG_PTR]],
	SetClassLongW: [DWORD, [HWND, INT, LONG]],
	SetClassWord: [WORD, [HWND, INT, WORD]],
	SetClipboardData: [HANDLE, [UINT, HANDLE]],
	SetClipboardViewer: [HWND, [HWND]],
	SetCoalescableTimer: [UINT_PTR, [HWND, UINT_PTR, UINT, TIMERPROC, ULONG]],
	SetCursor: [HCURSOR, [HCURSOR]],
	SetCursorPos: [BOOL, [INT, INT]],
	SetDialogControlDpiChangeBehavior: [BOOL, [HWND, DIALOG_CONTROL_DPI_CHANGE_BEHAVIORS, DIALOG_CONTROL_DPI_CHANGE_BEHAVIORS]],
	SetDialogDpiChangeBehavior: [BOOL, [HWND, DIALOG_DPI_CHANGE_BEHAVIORS, DIALOG_DPI_CHANGE_BEHAVIORS]],
	SetDisplayAutoRotationPreferences: [BOOL, [ORIENTATION_PREFERENCE]],
	SetDisplayConfig: [LONG, [UINT32, DISPLAYCONFIG_PATH_INFO, UINT32, DISPLAYCONFIG_MODE_INFO, UINT32]],
	SetDlgItemInt: [BOOL, [HWND, INT, UINT, BOOL]],
	SetDlgItemTextA: [BOOL, [HWND, INT, LPCSTR]],
	SetDlgItemTextW: [BOOL, [HWND, INT, LPCWSTR]],
	SetDoubleClickTime: [BOOL, [UINT]],
	SetFocus: [HWND, [HWND]],
	SetForegroundWindow: [BOOL, [HWND]],
	SetGestureConfig: [BOOL, [HWND, DWORD, UINT, PGESTURECONFIG, UINT]],
	SetKeyboardState: [BOOL, [LPBYTE]],
	SetLastErrorEx: [VOID, [DWORD, DWORD]],
	SetLayeredWindowAttributes: [BOOL, [HWND, COLORREF, BYTE, DWORD]],
	SetMenu: [BOOL, [HWND, HMENU]],
	SetMenuContextHelpId: [BOOL, [HMENU, DWORD]],
	SetMenuDefaultItem: [BOOL, [HMENU, UINT, UINT]],
	SetMenuInfo: [BOOL, [HMENU, LPCMENUINFO]],
	SetMenuItemBitmaps: [BOOL, [HMENU, UINT, UINT, HBITMAP, HBITMAP]],
	SetMenuItemInfoA: [BOOL, [HMENU, UINT, BOOL, LPCMENUITEMINFOA]],
	SetMenuItemInfoW: [BOOL, [HMENU, UINT, BOOL, LPCMENUITEMINFOW]],
	SetMessageExtraInfo: [LPARAM, [LPARAM]],
	SetParent: [HWND, [HWND, HWND]],
	SetPhysicalCursorPos: [BOOL, [INT, INT]],
	SetProcessDefaultLayout: [BOOL, [DWORD]],
	SetProcessDPIAware: [BOOL, []],
	SetProcessDpiAwarenessContext: [BOOL, [DPI_AWARENESS_CONTEXT]],
	SetProcessRestrictionExemption: [BOOL, [BOOL]],
	SetProcessWindowStation: [BOOL, [HWINSTA]],
	SetPropA: [BOOL, [HWND, LPCSTR, HANDLE]],
	SetPropW: [BOOL, [HWND, LPCWSTR, HANDLE]],
	SetRect: [BOOL, [LPRECT, INT, INT, INT, INT]],
	SetRectEmpty: [BOOL, [LPRECT]],
	SetScrollInfo: [INT, [HWND, INT, LPCSCROLLINFO, BOOL]],
	SetScrollPos: [INT, [HWND, INT, INT, BOOL]],
	SetScrollRange: [BOOL, [HWND, INT, INT, INT, BOOL]],
	SetSysColors: [BOOL, [INT, INT, COLORREF]],
	SetSystemCursor: [BOOL, [HCURSOR, DWORD]],
	SetThreadDesktop: [BOOL, [HDESK]],
	SetThreadDpiAwarenessContext: [DPI_AWARENESS_CONTEXT, [DPI_AWARENESS_CONTEXT]],
	SetThreadDpiHostingBehavior: [DPI_HOSTING_BEHAVIOR, [DPI_HOSTING_BEHAVIOR]],
	SetTimer: [UINT_PTR, [HWND, UINT_PTR, UINT, TIMERPROC]],
	SetUserObjectInformationA: [BOOL, [HANDLE, INT, PVOID, DWORD]],
	SetUserObjectInformationW: [BOOL, [HANDLE, INT, PVOID, DWORD]],
	SetUserObjectSecurity: [BOOL, [HANDLE, PSECURITY_INFORMATION, PSECURITY_DESCRIPTOR]],
	SetWindowContextHelpId: [BOOL, [HWND, DWORD]],
	SetWindowDisplayAffinity: [BOOL, [HWND, DWORD]],
	SetWindowFeedbackSetting: [BOOL, [HWND, FEEDBACK_TYPE, DWORD, UINT32, VOID]],
	SetWindowLongA: [LONG, [HWND, INT, LONG]],
	SetWindowLongPtrA: [LONG_PTR, [HWND, INT, LONG_PTR]],
	SetWindowLongPtrW: [LONG_PTR, [HWND, INT, LONG_PTR]],
	SetWindowLongW: [LONG, [HWND, INT, LONG]],
	SetWindowPlacement: [BOOL, [HWND, WINDOWPLACEMENT]],
	SetWindowPos: [BOOL, [HWND, HWND, INT, INT, INT, INT, UINT]],
	SetWindowRgn: [INT, [HWND, HRGN, BOOL]],
	SetWindowsHookExA: [HHOOK, [INT, HOOKPROC, HINSTANCE, DWORD]],
	SetWindowsHookExW: [HHOOK, [INT, HOOKPROC, HINSTANCE, DWORD]],
	SetWindowTextA: [BOOL, [HWND, LPCSTR]],
	SetWindowTextW: [BOOL, [HWND, LPCWSTR]],
	SetWinEventHook: [HWINEVENTHOOK, [DWORD, DWORD, HMODULE, WINEVENTPROC, DWORD, DWORD, DWORD]],
	ShowCaret: [BOOL, [HWND]],
	ShowCursor: [INT, [BOOL]],
	ShowOwnedPopups: [BOOL, [HWND, BOOL]],
	ShowScrollBar: [BOOL, [HWND, INT, BOOL]],
	ShowWindow: [BOOL, [HWND, INT]],
	ShowWindowAsync: [BOOL, [HWND, INT]],
	ShutdownBlockReasonCreate: [BOOL, [HWND, LPCWSTR]],
	ShutdownBlockReasonDestroy: [BOOL, [HWND]],
	ShutdownBlockReasonQuery: [BOOL, [HWND, LPWSTR, DWORD]],
	SkipPointerFrameMessages: [BOOL, [UINT32]],
	SoundSentry: [BOOL, []],
	SubtractRect: [BOOL, [LPRECT, RECT, RECT]],
	SwapMouseButton: [BOOL, [BOOL]],
	SwitchDesktop: [BOOL, [HDESK]],
	SwitchToThisWindow: [VOID, [HWND, BOOL]],
	SystemParametersInfoA: [BOOL, [UINT, UINT, PVOID, UINT]],
	SystemParametersInfoForDpi: [BOOL, [UINT, UINT, PVOID, UINT, UINT]],
	SystemParametersInfoW: [BOOL, [UINT, UINT, PVOID, UINT]],
	TabbedTextOutA: [LONG, [HDC, INT, INT, LPCSTR, INT, INT, INT, INT]],
	TabbedTextOutW: [LONG, [HDC, INT, INT, LPCWSTR, INT, INT, INT, INT]],
	TileWindows: [WORD, [HWND, UINT, RECT, UINT, HWND]],
	ToAscii: [INT, [UINT, UINT, BYTE, LPWORD, UINT]],
	ToAsciiEx: [INT, [UINT, UINT, BYTE, LPWORD, UINT, HKL]],
	// TOUCH_COORD_TO_PIXEL: [VOID, []],
	ToUnicode: [INT, [UINT, UINT, BYTE, LPWSTR, INT, UINT]],
	ToUnicodeEx: [INT, [UINT, UINT, BYTE, LPWSTR, INT, UINT, HKL]],
	TrackMouseEvent: [BOOL, [LPTRACKMOUSEEVENT]],
	TrackPopupMenu: [BOOL, [HMENU, UINT, INT, INT, INT, HWND, RECT]],
	TrackPopupMenuEx: [BOOL, [HMENU, UINT, INT, INT, HWND, LPTPMPARAMS]],
	TranslateAcceleratorA: [INT, [HWND, HACCEL, LPMSG]],
	TranslateAcceleratorW: [INT, [HWND, HACCEL, LPMSG]],
	TranslateMDISysAccel: [BOOL, [HWND, LPMSG]],
	TranslateMessage: [BOOL, [MSG]],
	UnhookWindowsHookEx: [BOOL, [HHOOK]],
	UnhookWinEvent: [BOOL, [HWINEVENTHOOK]],
	UnionRect: [BOOL, [LPRECT, RECT, RECT]],
	UnloadKeyboardLayout: [BOOL, [HKL]],
	UnregisterClassA: [BOOL, [LPCSTR, HINSTANCE]],
	UnregisterClassW: [BOOL, [LPCWSTR, HINSTANCE]],
	UnregisterDeviceNotification: [BOOL, [HDEVNOTIFY]],
	UnregisterHotKey: [BOOL, [HWND, INT]],
	UnregisterPointerInputTarget: [BOOL, [HWND, POINTER_INPUT_TYPE]],
	UnregisterPointerInputTargetEx: [BOOL, [HWND, POINTER_INPUT_TYPE]],
	UnregisterPowerSettingNotification: [BOOL, [HPOWERNOTIFY]],
	UnregisterSuspendResumeNotification: [BOOL, [HPOWERNOTIFY]],
	UnregisterTouchWindow: [BOOL, [HWND]],
	UpdateLayeredWindow: [BOOL, [HWND, HDC, POINT, SIZE, HDC, POINT, COLORREF, BLENDFUNCTION, DWORD]],
	UpdateWindow: [BOOL, [HWND]],
	UserHandleGrantAccess: [BOOL, [HANDLE, HANDLE, BOOL]],
	ValidateRect: [BOOL, [HWND, RECT]],
	ValidateRgn: [BOOL, [HWND, HRGN]],
	VkKeyScanA: [SHORT, [CHAR]],
	VkKeyScanExA: [SHORT, [CHAR, HKL]],
	VkKeyScanExW: [SHORT, [WCHAR, HKL]],
	VkKeyScanW: [SHORT, [WCHAR]],
	WaitForInputIdle: [DWORD, [HANDLE, DWORD]],
	WaitMessage: [BOOL, []],
	WindowFromDC: [HWND, [HDC]],
	WindowFromPhysicalPoint: [HWND, [POINT]],
	WindowFromPoint: [HWND, [POINT]],
	WinHelpA: [BOOL, [HWND, LPCSTR, UINT, ULONG_PTR]],
	WinHelpW: [BOOL, [HWND, LPCWSTR, UINT, ULONG_PTR]]
	// wsprintfA: [INTWINAPIV, [LPSTR, LPCSTR, ...]],
	// wsprintfW: [INTWINAPIV, [LPWSTR, LPCWSTR, ...]],
	// wvsprintfA: [INT, [LPSTR, LPCSTR, VA_LIST]],
	// wvsprintfW: [INT, [LPWSTR, LPCWSTR, VA_LIST]],
};

